name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy CI/CD Test App
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            mkdir /var/www/html/ci_cd 
            cd /var/www/html/ci_cd 
            git clone git@github.com:anilgupta1020/ci_cd_pipieline_v2.git
            echo 'Deployment successful to digital ocean
