name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy CI/CD Test App
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          
          script: |
            cd /var/www/html/ci_cd/ci_cd_pipieline_v2
            git pull origin main
            sudo pm2 restart 6
            echo Deployment successful to digital ocean